# Generated by Django 2.2 on 2022-06-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=32)),
                ('sprice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sage', models.CharField(max_length=32)),
                ('shome', models.CharField(max_length=32)),
            ],
        ),
    ]
